# Generated by Django 4.2.3 on 2023-08-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weave", "0002_alter_message_deleted_alter_person_deleted_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                condition=models.Q(("deleted", False)),
                fields=["deleted"],
                name="soft_deletes_ignore",
            ),
        ),
    ]
